name: mame
version: 'mame0285'
summary: Multiple Arcade Machine Emulator (MAME)
description: |
 MAME is a hardware emulator. it faithfully reproduces the behaviour of
 many arcade machines (it is not a simulation). This program is not a game
 but can directly, through ROM images, run the complete system of these old
 arcade machines. These ROMs are subject to copyright and it is in most of
 the cases illegal to use them if you do not own the arcade machine.
 .
 This package provides the MAME binary and configuration files.
base: core22
architectures:
  - build-on: amd64
  - build-on: arm64
confinement: strict
grade: stable
compression: lzo
apps:
  mame:
    command-chain:
      - snap/command-chain/alsa-launch
    extensions: [gnome]
    command: mame
    plugs:
      - alsa
      - unity7
      - network
      - network-bind
      - home
      - opengl
      - audio-playback
      - mount-observe
      - optical-drive
      - joystick
      - screen-inhibit-control
      - removable-media
      - hardware-observe
      - process-control

parts:
  alsa-mixin:
    plugin: nil
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    override-pull: |
      cat > asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      seq.default {
          type hw
      }
      seq.hw {
          type hw
      }
      EOF
      cat > alsa-launch <<EOF
      #!/bin/bash
      export ALSA_CONFIG_PATH="\$SNAP/etc/asound.conf"

      if [ -d "\$SNAP/usr/lib/alsa-lib" ]; then
          export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:\$SNAP/usr/lib/alsa-lib"
      elif [ -d "\$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib" ]; then
          export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:\$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib"
      fi
      export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:\$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"

      # Make PulseAudio socket available inside the snap-specific \$XDG_RUNTIME_DIR
      if [ -n "\$XDG_RUNTIME_DIR" ]; then
          pulsenative="pulse/native"
          pulseaudio_sockpath="\$XDG_RUNTIME_DIR/../\$pulsenative"
          if [ -S "\$pulseaudio_sockpath" ]; then
              export PULSE_SERVER="unix:\${pulseaudio_sockpath}"
          fi
      fi

      exec "\$@"
      EOF
      chmod +x alsa-launch
    override-build: |
      snapcraftctl build
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc asound.conf
      install -m755 -D -t $SNAPCRAFT_PART_INSTALL/snap/command-chain alsa-launch
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - inotify-tools
  mame:
    after: [alsa-mixin]
    plugin: make
    source: https://github.com/mamedev/mame.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-type: git
    #make-parameters:  [CFLAGS="-fpch-preprocess", CXXFLAGS="-fpch-preprocess", CC="gcc-10", CXX="g++-10"]
    override-build: |
      export QT_SELECT="5"
      export CFLAGS+="-fpch-preprocess"
      export CXXFLAGS+="-fpch-preprocess"
      make NOWERROR='1' OPTIMIZE='2' TOOLS='1' -j$((`nproc`+1))
      install -D -m755 mame $SNAPCRAFT_PART_INSTALL/mame
    build-packages:
      - gcc-10
      - g++-10
      - libexpat1-dev
      - libflac-dev
      - libfontconfig1-dev
      - libjpeg-dev
      - libpugixml-dev
      - libportmidi-dev
      - qtdeclarative5-dev
      - qtbase5-dev
      - libsdl2-ttf-dev
      - libsdl2-dev
      - libutf8proc-dev
      - libsqlite3-dev
      - libxinerama-dev
      - portaudio19-dev
      - python3-dev
      - rapidjson-dev
      - zlib1g-dev
      - libqt5core5a
      - libasio-dev
      - libglm-dev
    stage-packages:
      - libass9
      - libbluetooth3
      - libbz2-1.0
      - libcdio19
      - libcurl4
      - libcrossguid0
      - libdbus-1-3
      - libdrm2
      - libexpat1
      - libfreetype6
      - libfribidi0
      - libgcc1
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglew2.2
      - libgmp10
      - libjpeg8
      - liblzma5
      - liblzo2-2
#      - libmpeg2-4
      - libogg0
      - libpcre3
      - libpcrecpp0v5
      - libpng16-16
      - libpulse0
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
      - libssh-4
      - libstdc++6
      - libtag1v5
      - libtiff5
      - libtinyxml2.6.2v5
      - libudev1
      - libva-x11-2
      - libva2
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libx11-6
      - libxext6
      - libxml2
      - libxrandr2
      - libxslt1.1
      - libyajl2
      - zlib1g
      - libdouble-conversion3
      - libpcre2-16-0
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
